### ISSUE TITLE
MIT licensed StyleTTS2 Python package

### ISSUE THREAD

**Issue by sidharthrajaram** [NeuralVox/StyleTTS2-Browser-Extension#1]
Hey @fakerybakery , I saw you were part of the discussions about the StyleTTS2 inference stack's licensing issues.  I figured you might find this interesting: it's a [pip installable package that does StyleTTS2 inference](https://pypi.org/project/styletts2/). Feel free to check it out! 

AI-read audiobooks is a great idea. Also I think the sample audio of 'The Raven' leads to a broken link?

**Comment by fakerybakery** [comment]
Nice! Yeah, "The Raven" was read using Tortoise TTS - I switched my website a while back so the links got deleted. Sorry about that - I'll fix it soon. 

The importable package looks really cool! Might you consider adding STTS as a sub module to keep it up to date, with GH actions to automatically update it?

**Comment by sidharthrajaram** [comment]
Ah, I see. No problem! 

Thanks, yeah that's the plan 😃

**Comment by fakerybakery** [comment]
Hi,
Here is the audio file for "The Raven" read by Tortoise TTS:

https://github.com/NeuralVox/StyleTTS2-Browser-Extension/assets/76186054/92a563d1-6c26-4df9-ba10-8b82165ef527

**Comment by sidharthrajaram** [comment]
Wow, the intonations were great!

In your (and NeuralVox's) experience, how does StyleTTS2 stack up to Tortoise?

**Comment by fakerybakery** [comment]
Hmm. Well Tortoise is _very_ slow. It took several hours to create "The Raven" on a free Colab (T4). Also, Tortoise barely fits on Colab's memory, so it keeps crashing and I have to manually restart it and modify the code to start from the correct place. Tortoise definitely handles emotions, intonations, etc really well. On StyleTTS w/ the same hardware, it would probably take <10 seconds. There would probably be basically no emotion.

So, the tradeoff is speed/compute. If you have lots of compute/are willing to wait a long time, I'd go with Tortoise. However, if you're concerned about speed, I think StyleTTS is better. Also, the LJSpeech model is a bit better than the voice cloning model.

Here's an example w/ StyleTTS 2:

https://github.com/NeuralVox/StyleTTS2-Browser-Extension/assets/76186054/3864bc49-f23d-42da-a1fd-198623b60f8f

**Comment by fakerybakery** [comment]
I think the main thing making StyleTTS more "bland" is the training data. StyleTTS is trained on LibriVox, because LibriVox audiobooks are in the public domain. Parts of Tortoise strongly suggest it's trained on professional audiobooks (not sure how the legal stuff works out) narrated by professional voice actors, so maybe that's why. Personally, I think StyleTTS could be greatly improved if they had a more varied training dataset, but I'm not an expert.
